"""Author the two planned-but-missing guesstimates (metro-ticketing-revenue,
coffee-sachets-daily). Every `result` is computed by evaluating its `expr`, so
the published arithmetic cannot drift from the published working.

Grounding (Placements folder casebooks):
- IIM Calcutta casebook, "Estimate Annual Revenue of Mumbai Local Train Network":
  key learnings "Behavioural segmentation (passes vs tickets) improves accuracy"
  and "convert monthly prices into per-use values". Its worked solution also
  multiplies daily trips by the monthly pass price, which the metro entry
  teaches as a trap (described, not attributed).
- IIM Ahmedabad prep book, Guesstimate 25 (Delhi Metro Yellow Line ridership
  from train capacity) -> the metro entry's supply-side triangulation.
- IIM Calcutta casebook, "Cup Noodles Sold per Day in India" (awareness ->
  trial -> repeat funnel, urban/rural split) and "Cups of Tea Consumed Daily":
  "Frequency of usage is more important than just user count";
  "In habit-based products, think in terms of occasions per day".
"""
import io, json, re

SAFE = re.compile(r"^[0-9.+\-*/() \t]+$")
def ev(expr):
    assert SAFE.match(expr), expr
    return eval(expr, {"__builtins__": {}}, {})

def line(i, label, expr, display, unit, carried, uses, so_what, prefix="c"):
    r = ev(expr)
    r = int(r) if abs(r - round(r)) < 1e-9 else round(r, 6)
    return {"id": f"{prefix}{i}", "label": label, "expr": expr, "display": display, "result": r,
            "tolerance": 0, "unit": unit, "carriedForward": carried, "uses": uses, "soWhat": so_what}

def A(id_, lever, value, numeric, unit, basis, defence, confidence, contested):
    return {"id": id_, "lever": lever, "value": value, "numeric": numeric, "unit": unit, "basis": basis,
            "defence": defence, "confidence": confidence, "contestedBy": contested}

# =====================================================================================
# 1. METRO FARE REVENUE
# =====================================================================================
metro_assumptions = [
    A("a-city-pop", "Population of the city", "2 crore (20 Mn)", 20000000, "people", "declared-judgement",
      "The scope of the question, not a finding: one large Indian city with a mature, multi-line metro. Fixing it up front keeps every later number tied to a place you can picture.",
      "anchor", "A smaller city with a younger network changes the rider share far more than it changes the population — carry the city as given and argue about the share."),
    A("a-rider-share", "Share of residents who ride on a working day", "8%", 0.08, "share", "declared-judgement",
      "Most residents never touch the metro on a given day: it serves some corridors well and others not at all, and many trips are short, local or by two-wheeler. One resident in twelve on a working day is a mature network, not a new one.",
      "shaky", "A young network might be 3%; a dense, well-connected one could pass 12%. This is the single shakiest input, and every line below is linear in it."),
    A("a-pass-share", "Share of working-day riders on a monthly pass", "40%", 0.4, "share", "observed-behaviour",
      "Passes are bought by people who ride the same route twice a day, five or six days a week. They are a minority of everyone who rides in a month but a large share of the people riding on any one working day — because they are there every day and occasional riders are not.",
      "judgement", "A network that sells only stored-value cards has no pass regime at all; one with a generous student pass could be above half."),
    A("a-pass-trips", "Journeys a pass holder makes on a working day", "2", 2, "journeys a day", "structural-logic",
      "Out and back. Some add a midday trip and some take a lift one way, but two is the number a commuter pass is priced around.",
      "defensible", "Hybrid working pulls it below two on average; a holder who also rides on Saturdays pushes the monthly count up."),
    A("a-ppr-trips", "Journeys a pay-per-ride rider makes on a day they ride", "1.6", 1.6, "journeys a day", "observed-behaviour",
      "Occasional riders often make a return trip, but a meaningful minority ride one way — to a station, then a cab or a lift home.",
      "judgement", "Tourists and shoppers can make three or four hops in a day; the blend barely moves the answer."),
    A("a-days-month", "Working days in a month", "25", 25, "days", "structural-logic",
      "A six-day week less holidays for many workplaces and a five-day week for others; 25 is the working count a monthly pass is bought against.",
      "defensible", "A strictly five-day workforce gives 22, which raises the implied fare per pass ride to about ₹23."),
    A("a-pass-price", "Monthly pass price", "₹1,000", 1000, "₹ a month", "declared-judgement",
      "Priced so a daily commuter saves clearly against paying per ride — the point of a pass is to lock in the heaviest users. ₹1,000 against fifty rides is ₹20 a ride.",
      "judgement", "Some systems sell trip-packs of 40–50 journeys rather than unlimited months; the per-ride arithmetic is identical."),
    A("a-months", "Months of pass sales in a year", "12", 12, "months", "structural-logic",
      "Holders who let a pass lapse in a holiday month are roughly offset by new holders joining; twelve full months is the honest simplification.",
      "anchor", "A strongly seasonal city — a college town emptying in summer — would take a month or two off."),
    A("a-fare", "Average fare per pay-per-ride journey", "₹35", 35, "₹ a journey", "declared-judgement",
      "Indian metro fares are distance-slab tables that start around ₹10; a typical 12–15 km journey falls in the middle of the table, with the small stored-value-card discount taken off.",
      "defensible", "A network of short feeder trips averages nearer ₹25; long cross-city commutes on a high-slab table push it past ₹45."),
    A("a-work-days-year", "Working days in a year", "300", 300, "days", "structural-logic",
      "Twenty-five working days a month, twelve months. It must match the monthly figure used for the pass, or the two regimes are annualised on different calendars.",
      "defensible", "A five-day-week city is nearer 250; the pay-per-ride line falls by about 7%."),
    A("a-off-days", "Sundays and holidays in a year", "65", 65, "days", "structural-logic",
      "Whatever is not a working day: 365 less 300.",
      "anchor", "Follows mechanically from the working-day count."),
    A("a-off-factor", "Pay-per-ride travel on a non-working day, versus a working day", "55%", 0.55, "share", "observed-behaviour",
      "Commuters vanish on a Sunday; shoppers, families and weekend visitors partly replace them. Only pay-per-ride travel counts here — a pass holder's Sunday ride was already paid for with the month.",
      "judgement", "Cities with a strong weekend leisure economy run close to 70%; industrial ones fall below 40%."),
    # triangulation inputs
    A("a-lines", "Lines in the network", "8", 8, "lines", "declared-judgement",
      "A mature network in a city of this size — the same picture the population assumption sets up.",
      "judgement", "Fewer, longer lines carry similar volumes with fewer interchanges."),
    A("a-runs", "Train runs per line per direction on a working day", "170", 170, "runs", "structural-logic",
      "A train every five to seven minutes on average over an eighteen-hour operating day is about 150–220 runs each way; rush-hour headways are tighter and late-evening ones wider.",
      "defensible", "Busy trunk lines run far more; new branch lines far fewer."),
    A("a-train-cap", "Passengers a six-coach train carries at a practical full load", "1,500", 1500, "passengers", "declared-judgement",
      "About 250 a coach standing and seated at a practical full load. Crush loads in the rush hour are higher, which is exactly why they are not the average.",
      "defensible", "Eight-coach trains on trunk lines carry about a third more."),
    A("a-load", "Average occupancy across every run of the day", "35%", 0.35, "share", "observed-behaviour",
      "Peak-direction trains in the rush hour run full; counter-peak, midday and late trains run nearly empty. Averaged over every run, about a third of capacity is used.",
      "shaky", "Anything from 25% to 45% is defensible, which moves the supply figure by about 30% either way."),
    A("a-turnover", "Times each place is refilled along a run", "2.5", 2.5, "refills a run", "structural-logic",
      "An average journey covers about 40% of a line's length, so each place is used about two and a half times over one end-to-end run.",
      "judgement", "Short-hop, dense-station lines turn over faster; airport lines hardly turn over at all."),
    A("a-interchange", "Line-boardings per journey", "1.25", 1.25, "boardings a journey", "observed-behaviour",
      "About a quarter of journeys change lines once. A line-level count sees them twice; the farebox charges them once, gate in to gate out.",
      "judgement", "Radial networks with a single central interchange run higher."),
]

metro_calc = [
    line(1, "Riders on a working day", "20000000 * 0.08", "2 crore residents × 8%", "riders", "16 lakh riders",
         ["a-city-pop", "a-rider-share"],
         "The shakiest number in the tree, and every line below is linear in it. Box it, and argue about it once rather than on every line."),
    line(2, "Pass holders", "1600000 * 0.4", "16 lakh × 40%", "holders", "6.4 lakh holders", ["a-pass-share"],
         "People, not journeys. A monthly price is only ever multiplied by people."),
    line(3, "Pay-per-ride riders on a working day", "1600000 * 0.6", "16 lakh × 60%", "riders", "9.6 lakh riders", ["a-pass-share"],
         "The other 60%. They pay by the ride, so from here they are counted in journeys."),
    line(4, "Rides a pass holder takes in a month", "2 * 25", "2 journeys × 25 working days", "rides a month", "50 rides",
         ["a-pass-trips", "a-days-month"],
         "The denominator for the most important division in the question."),
    line(5, "What a pass holder pays per ride", "1000 / 50", "₹1,000 ÷ 50 rides", "₹ a ride", "₹20 a ride", ["a-pass-price"],
         "This is the move the question exists to test. A pass holder pays ₹20 a ride against ₹35 for a token — the heaviest users pay the least. Say it before you multiply anything, and the pass line cannot be double-counted."),
    line(6, "Pass revenue in a year", "640000 * 1000 * 12", "6.4 lakh holders × ₹1,000 × 12 months", "₹ a year", "₹768 crore",
         ["a-pass-price", "a-months"],
         "Annualised by months, because that is how a pass is bought. Multiplying by working days here would price each holder at ₹3 lakh a year."),
    line(7, "Pay-per-ride journeys on a working day", "960000 * 1.6", "9.6 lakh riders × 1.6 journeys", "journeys a day", "15.4 lakh journeys",
         ["a-ppr-trips"],
         "Together with the 12.8 lakh pass journeys this is 28.2 lakh journeys on a working day. Pass holders are 40% of the riders but 45% of the journeys."),
    line(8, "Working-day equivalents in a year", "300 + 65 * 0.55", "300 working days + 65 days × 55%", "day-equivalents", "335.75",
         ["a-work-days-year", "a-off-days", "a-off-factor"],
         "Weekends belong to the pay-per-ride line only. A pass holder's Sunday ride earns the network nothing extra."),
    line(9, "Pay-per-ride journeys in a year", "1536000 * 335.75", "15.36 lakh × 335.75", "journeys a year", "51.6 crore journeys", [],
         "Over half the year's journeys, and — as the next line shows — over two-thirds of its money."),
    line(10, "Pay-per-ride revenue in a year", "515712000 * 35", "51.6 crore journeys × ₹35", "₹ a year", "₹1,805 crore", ["a-fare"],
         "The larger line by far, and the only one the average fare touches."),
    line(11, "Total farebox in a year", "7680000000 + 18049920000", "₹768 crore passes + ₹1,805 crore pay-per-ride", "₹ a year", "₹2,573 crore", [],
         "Passes are 30% of the money on 45% of the working-day journeys. If your pass line came out with a larger share of revenue than of journeys, you priced it per trip."),
    line(12, "Total farebox in crore", "25729920000 / 10000000", "₹25,730 Mn ÷ 1 crore", "₹ crore a year", "≈ ₹2,500 crore — round it before you say it", [],
         "Say ₹2,500 crore. The rider share alone could move it by a quarter; four significant figures would claim a precision nothing above supports."),
]

metro_tri = [
    line(1, "Train runs on a working day", "8 * 170 * 2", "8 lines × 170 runs × 2 directions", "runs", "2,720 runs", ["a-lines", "a-runs"],
         "Supply starts from what the timetable can run, not from who wants to ride.", prefix="t"),
    line(2, "Places offered", "2720 * 1500", "2,720 runs × 1,500 places", "places", "40.8 lakh places", ["a-train-cap"],
         "A ceiling, not a count — most of these places run empty.", prefix="t"),
    line(3, "Places occupied, on average", "4080000 * 0.35", "40.8 lakh × 35% occupancy", "places", "14.3 lakh", ["a-load"],
         "The load factor is the shakiest number on this side, and it is shaky in a useful way: full rush-hour trains are a peak fact, not an all-day one.", prefix="t"),
    line(4, "Line-boardings", "1428000 * 2.5", "14.28 lakh × 2.5 refills", "boardings", "35.7 lakh boardings", ["a-turnover"],
         "Each place is used about two and a half times along a run.", prefix="t"),
    line(5, "Journeys on a working day", "3570000 / 1.25", "35.7 lakh boardings ÷ 1.25 per journey", "journeys", "28.6 lakh journeys", ["a-interchange"],
         "Against 28.2 lakh from the demand route. Priced once per journey, gate in to gate out.", prefix="t"),
]

metro = {
    "id": "metro-ticketing-revenue",
    "question": "What does a city metro network collect in fares over a year?",
    "tabLabel": "Metro fares, one city",
    "archetype": "network-price-mix",
    "difficulty": "Medium",
    "timeboxMinutes": 12,
    "teachingPoint": "A monthly pass and a token are two different prices for the same ride, and the pass is the one that misleads. Convert it into what a holder actually pays per ride before you multiply anything: ₹1,000 a month across fifty rides is ₹20 a ride, against ₹35 for a token. Split people before you apply a monthly price and journeys before you apply a per-ride one, and the two regimes cannot contaminate each other.",
    "scope": {
        "countingWhat": "Fare revenue — money collected at the farebox — over one year by a single large metro rail network in one Indian city. Passes, tokens, QR tickets and stored-value cards count; nothing else does.",
        "unit": "₹ crore a year",
        "timeBasis": "flow (per year)",
        "geography": "One illustrative Indian city of 2 crore people with a mature metro of about eight lines.",
        "included": [
            "Monthly passes and trip-packs bought by daily commuters",
            "Single-journey tokens and QR tickets",
            "Stored-value smart cards, at their discounted per-ride fare",
            "Weekend and holiday travel by occasional riders",
        ],
        "excluded": [
            "Advertising, station retail and property development income",
            "Parking and feeder-bus fares",
            "Consultancy and other non-transport income",
            "Fines and penalty fares",
            "Suburban rail and city buses",
        ],
        "boundaryTrap": "An operator's headline revenue usually includes property, advertising and consultancy income, which can be a large share of the total. This question is the farebox alone. Watch the volume side too: published ridership is often counted by line, which counts a passenger who changes lines twice, while a fare is charged once per journey.",
    },
    "routeChoice": {
        "chosen": "Hybrid",
        "why": "The riders come top-down — residents, then the share who ride on a working day — because nobody can count a metro's riders from the bottom in an interview. The money comes bottom-up, product by product, because a pass and a token price the same ride differently and that difference is the question.",
        "rejectedRoute": "Top-down",
        "rejectedWhyNot": "A pure top-down route — riders × journeys × one average fare × days — needs a single average fare, and there is no honest single fare when four in ten of the day's riders prepay for the month. Choosing that number is exactly where the answer goes wrong, so the route has to split before it prices.",
    },
    "tree": {
        "root": "Annual farebox of one city metro network",
        "rootFormula": "= (Pass holders × monthly pass price × 12) + (Pay-per-ride journeys a year × average fare)",
        "value": "≈ ₹2,570 crore",
        "branches": [
            {"label": "Pay-per-ride — tokens, QR tickets, stored-value cards",
             "formula": "9.6 lakh riders × 1.6 journeys × 335.75 day-equivalents × ₹35",
             "value": "51.6 crore journeys · ₹1,805 crore",
             "note": "70% of the money. Weekends and holidays belong here: pass-holding commuters vanish on a Sunday, occasional riders do not.",
             "isCriticalPath": True,
             "children": [
                 {"label": "Journeys on a working day", "formula": "9.6 lakh × 1.6", "value": "15.4 lakh",
                  "note": "Fewer journeys a head than a commuter, because some occasional riders go one way only."},
                 {"label": "Working-day equivalents a year", "formula": "300 + 65 × 55%", "value": "335.75",
                  "note": "Sundays and holidays count at a little over half a working day."},
                 {"label": "Average fare", "formula": "Middle of a distance-slab table", "value": "₹35 a journey",
                  "note": "The only lever that moves this line and leaves the pass line untouched."},
             ]},
            {"label": "Pass holders — daily commuters",
             "formula": "16 lakh riders × 40% × ₹1,000 × 12 months",
             "value": "6.4 lakh holders · ₹768 crore",
             "note": "Priced by the month, not the ride. 45% of working-day journeys and 30% of the money — the gap between those two shares is the whole lesson.",
             "isCriticalPath": False,
             "children": [
                 {"label": "Riders on a working day", "formula": "2 crore residents × 8%", "value": "16 lakh",
                  "note": "The shakiest number in the tree; both branches inherit it."},
                 {"label": "Implied fare per pass ride", "formula": "₹1,000 ÷ (2 journeys × 25 days)", "value": "₹20 a ride",
                  "note": "Against ₹35 for a token. The heaviest users pay the least per ride — say it out loud."},
             ]},
        ],
    },
    "assumptions": metro_assumptions,
    "calculation": metro_calc,
    "finalAnswer": "≈ ₹2,500 crore a year in fares, for an illustrative network carrying about 28 lakh journeys on a working day. Pass holders make 45% of working-day journeys but pay 30% of the money, because a pass works out at ₹20 a ride against ₹35 for a token.",
    "finalAnswerNumeric": 2500,
    "answerBand": "₹1,900 – ₹3,500 crore a year. The band is set mostly by the rider share — 8% of residents on a working day could credibly be 6% or 11% — and secondly by the pay-per-ride fare, which swings the larger revenue line by about a fifth either way.",
    "orderOfMagnitude": "10^10 rupees (₹2,500 crore ≈ ₹2.6 × 10^10); about 10^9 journeys a year",
    "triangulation": {
        "label": "Supply-side cross-check — could the network physically carry this many journeys?",
        "route": "Bottom-up",
        "premise": "Count what the trains can carry instead of who rides them: runs a day, places a run, how full the runs actually are, how many times a place is refilled along a run, and how many line-boardings make one journey. The route shares no inputs with the demand route, so agreement on volume is real evidence — but it cannot price anything, so it says nothing about the pass-versus-token split.",
        "lines": metro_tri,
        "answer": "≈ 28.6 lakh journeys on a working day, against 28.2 lakh from the demand route (12.8 lakh on passes, 15.4 lakh pay-per-ride).",
        "verdict": "Within about 1.5% on volume, from two routes that share no inputs — better agreement than either route deserves, since the load factor alone could move the supply figure by 30%. The claim to make is that the demand funnel is not inventing riders the network could not carry, not that the answer is confirmed. Revenue is untested by this route: it knows how many journeys there are, not what each one paid.",
    },
    "sensitivity": {
        "assumptionId": "a-fare",
        "whyThisLever": "The rider share is shakier, but it scales every line equally and teaches nothing. The pay-per-ride fare earns the grid because it moves only 70% of the answer: the pass line does not move at all, which is exactly what a pass is for — it turns a volatile per-ride income into a fixed monthly one.",
        "cases": [
            {"scenario": "Conservative", "leverValue": "₹25 a journey (short feeder trips, low slabs)", "answer": "≈ ₹2,060 crore", "deltaVsBase": "−20%"},
            {"scenario": "Base", "leverValue": "₹35 a journey", "answer": "≈ ₹2,570 crore", "deltaVsBase": "0%"},
            {"scenario": "Aggressive", "leverValue": "₹45 a journey (long cross-city commutes)", "answer": "≈ ₹3,090 crore", "deltaVsBase": "+20%"},
        ],
        "breakpoint": "The pay-per-ride fare would have to fall to about ₹15 before the two regimes brought in equal money — below any realistic average fare. Passes stay the minority of the revenue in every plausible case, even though they are close to half of the working-day journeys.",
        "oneLiner": "Every ₹10 on the average fare moves the answer by about ₹515 crore — and moves the pass line by nothing.",
    },
    "sanityChecks": [
        "₹2,573 crore across about 90 crore journeys a year is ₹28.6 a journey — between the ₹20 a pass holder pays per ride and the ₹35 a token costs, and closer to the token because pay-per-ride journeys are the majority of the year's trips. A blended fare outside that ₹20–₹35 range would mean a line had been priced twice.",
        "Per resident, the city spends ₹1,286 a year on metro fares — about ₹107 a month. A single pass holder's month is ₹1,000, so the whole city spends roughly what one resident in ten would if everyone else stayed home.",
        "Pass holders are 40% of working-day riders, 45% of working-day journeys and 30% of the money. Revenue share below journey share is the signature of a discounted product; the reverse would mean the pass had been priced per journey.",
        "The supply side needs only a 35% average load to carry the demand figure. An estimate that needed trains 90% full across the whole day would mean the rider share was too high — full trains are a rush-hour, peak-direction fact.",
        "Twenty-eight lakh journeys on a working day across sixteen lakh riders is 1.76 journeys each — two for pass holders, 1.6 for everyone else. A working-day figure above about 2.5 journeys a rider would mean line changes had been counted as journeys.",
        "The two common errors land together: pricing pass rides at the token fare gives about ₹3,150 crore, and multiplying journeys by the pass price about ₹3,340 crore. An answer in that range is a flag, not a coincidence.",
    ],
    "traps": [
        {"trap": "Pricing every ride at the token fare.",
         "whyItHappens": "The token price is the only metro fare most candidates can quote, and one price across one ride count feels clean. It ignores that the heaviest users — the ones there every working day — pay the least per ride.",
         "fix": "Convert the pass into its implied per-ride price first: ₹1,000 ÷ 50 rides is ₹20, not ₹35. Priced at the token fare, the pass line comes out at ₹1,344 crore instead of ₹768 crore — 75% too high — and the total 22% too high."},
        {"trap": "Multiplying journeys by the monthly pass price.",
         "whyItHappens": "After journeys are split into pass and token, the pass share of journeys looks like a count of pass holders. It is not: every holder makes two journeys a day. A worked solution to a suburban-rail version of this question in circulation makes exactly this slip.",
         "fix": "Split people, not journeys, before applying a monthly price. 6.4 lakh holders × ₹1,000 × 12 is ₹768 crore; 12.8 lakh pass journeys × ₹1,000 × 12 would be ₹1,536 crore — double, because each holder was counted once per trip."},
        {"trap": "Annualising the pass by days.",
         "whyItHappens": "Every other line in the tree is multiplied up by working days, so the pass line gets the same treatment by momentum.",
         "fix": "A pass is bought monthly: holders × price × 12. Multiplying by 300 working days prices each holder at ₹3 lakh a year, which is a car, not a metro pass."},
        {"trap": "Counting line-boardings as journeys.",
         "whyItHappens": "Line-level ridership is the figure most often reported, and it counts a passenger who changes lines once on each line.",
         "fix": "Fares are charged once per journey, gate in to gate out. Divide line-boardings by the interchange factor — 1.25 here — before pricing anything."},
        {"trap": "Adding pass holders' weekend rides to revenue.",
         "whyItHappens": "The weekend multiplier gets applied to all journeys, the pass holders' included, and their Sunday trips then earn a token fare.",
         "fix": "A pass holder's extra rides are free at the margin — the month paid for them. Apply the weekend factor to pay-per-ride travel only."},
        {"trap": "Starting from the whole city and a daily trip rate.",
         "whyItHappens": "Population × trips per person per day is the reflex for any transport question, and it silently assumes everyone in the city uses the metro.",
         "fix": "Gate on the share of residents who ride on a working day — 8% here — before counting a single journey. A metro serves corridors, not a whole city."},
    ],
    "probes": [
        {"question": "Pass holders make 45% of working-day journeys and pay 30% of the fares. Should the metro raise the pass price?",
         "intent": "Whether the candidate can read a pricing decision off the split, rather than treating the gap as underpricing.",
         "goodAnswer": "Not necessarily. A pass sells a guaranteed base load and cash up front, and it is the product that keeps commuters off the roads at the peak. The sharper question is when pass journeys happen: at the peak, where trains are full and the discount buys nothing, or off-peak, where it fills empty seats. An off-peak or peak-surcharged pass could protect revenue without losing the regulars.",
         "weakAnswer": "Yes — pass holders pay less per ride, so the metro is leaving money on the table."},
        {"question": "Where does your ₹20 per pass ride come from, and what would move it?",
         "intent": "Whether the implied fare is understood as a derived number rather than a posted one.",
         "goodAnswer": "It is the monthly price divided by the rides a holder actually takes — ₹1,000 ÷ 50. A holder who adds a midday trip and rides on Saturdays pays less per ride; one who works from home two days a week pays more. The realised fare on passes falls as their users ride more, which is why the posted price alone cannot be multiplied through.",
         "weakAnswer": "It's the pass fare."},
        {"question": "The city opens two new lines next year. What happens to your answer?",
         "intent": "Whether the candidate sees network effects rather than scaling by track length.",
         "goodAnswer": "The rider share rises by more than the added length, because each new line makes new journeys possible on the old lines too. The interchange factor rises, so line-level ridership grows faster than journeys. Pass uptake rises as more commutes become metro end to end. Revenue grows — but the average fare per journey can fall if the new lines mostly carry short feeder trips.",
         "weakAnswer": "Add a quarter to the answer, because there is a quarter more track."},
        {"question": "Your supply check agreed within 2%. Should that make you more confident?",
         "intent": "Triangulation humility.",
         "goodAnswer": "About the volume, somewhat: the two routes share no inputs. About the revenue, not at all — capacity knows how many journeys there are, not what each paid, so the pass-versus-token split is untouched. And the 35% load factor could as easily be 25% or 45%, which would move the supply figure by about 30%; the tightness of the agreement is partly luck.",
         "weakAnswer": "Yes — two methods agree, so the number is right."},
        {"question": "If you could ask the operator for one number, what would it be?",
         "intent": "Whether the candidate knows which inputs dominate.",
         "goodAnswer": "Journeys by ticket type, with the average fare on each — how many were made on passes and how many paid per ride. That replaces the rider share, the pass share and the fare in one stroke. Total ridership alone would help much less, because the revenue question is about the mix.",
         "weakAnswer": "Total daily ridership."},
    ],
}

# =====================================================================================
# 2. COFFEE SACHETS A DAY
# =====================================================================================
coffee_assumptions = [
    A("a-pop", "Population of India", "1.4 bn (140 crore)", 1400000000, "people", "census-anchor",
      "The working anchor in every Indian sizing question; the published figure sits a little above it, and rounding down buys arithmetic you can run in your head.",
      "anchor", "Some datasheets use 1.45 bn. Every figure below rises about 4% — not enough to change any conclusion here."),
    A("a-age", "Share of Indians in the coffee-drinking band, 15–60", "60%", 0.6, "share", "structural-logic",
      "Children rarely drink coffee and the over-60s drink less; the working-age band carries almost all of it. Sixty per cent is the band rounded down.",
      "defensible", "Official age tables put the 15–64 share nearer two-thirds; widening the band that far adds about a tenth to every line."),
    A("a-urban-share", "Urban share of the band", "35%", 0.35, "share", "census-anchor",
      "The same urban share used across the site's India questions; urban and rural are run as two separate funnels from here.",
      "defensible", "Definitions of 'urban' vary; the split matters far more than its exact position."),
    A("a-aware-u", "Urban awareness of instant coffee", "90%", 0.9, "share", "observed-behaviour",
      "Instant coffee sits on every urban kirana shelf and in every office pantry. Not having heard of it is rare.",
      "defensible", "Awareness is not the binding gate in cities, so its exact value hardly matters."),
    A("a-trial-u", "Urban trial — has bought or drunk instant coffee at least once", "45%", 0.45, "share", "declared-judgement",
      "A first cup at a hostel, an office or a friend's house. Tea is the default, so trial is far from universal even where awareness is total.",
      "judgement", "Younger urban cohorts run well above half; older ones well below. This is one of the two levers that decide the answer."),
    A("a-repeat-u", "Urban repeat — triers who buy at least once a month", "35%", 0.35, "share", "declared-judgement",
      "Most people who try instant coffee go back to tea. A third becoming regular buyers is a strong habit for a second-choice drink.",
      "judgement", "A strong premix launch or an office full of coffee drinkers pushes it higher; it rarely passes half."),
    A("a-freq-u", "Cups a week, per urban repeat buyer", "4", 4, "cups a week", "observed-behaviour",
      "A blend of daily desk drinkers and weekend or exam-season ones. Four a week is the blended figure, not the typical heavy user.",
      "shaky", "Anything from two to seven is defensible, and this lever alone moves the answer by −40% to +60%."),
    A("a-sachet-u", "Share of urban repeat buyers' cups made from a sachet", "50%", 0.5, "share", "structural-logic",
      "Heavy urban drinkers trade up to jars and pouches, which cost less per cup; sachets stay in the desk drawer and the travel bag.",
      "judgement", "Premix drinkers are almost all-sachet; jar loyalists almost none."),
    A("a-aware-r", "Rural awareness of instant coffee", "55%", 0.55, "share", "observed-behaviour",
      "Stocked in market towns and larger villages, often absent in smaller ones. Television reach carries awareness past distribution.",
      "judgement", "Awareness is not rural India's binding gate either — trial is."),
    A("a-trial-r", "Rural trial", "15%", 0.15, "share", "declared-judgement",
      "The binding number. Rural India drinks tea by default, and coffee is unfamiliar outside the South, where the habit is filter coffee rather than instant.",
      "shaky", "Doubling it doubles the rural line — which is exactly why a brand would spend there."),
    A("a-repeat-r", "Rural repeat", "25%", 0.25, "share", "declared-judgement",
      "Lower than urban: fewer outlets stock it reliably, and tea is cheaper still.",
      "judgement", "Distribution depth, not preference, is most of the gap."),
    A("a-freq-r", "Cups a week, per rural repeat buyer", "2", 2, "cups a week", "declared-judgement",
      "An occasional treat or a winter habit rather than a daily ritual.",
      "shaky", "Winter months run higher; a daily rural coffee habit is rare outside the South."),
    A("a-sachet-r", "Share of rural repeat buyers' cups made from a sachet", "90%", 0.9, "share", "structural-logic",
      "The sachet is the rural format: a few rupees' outlay, no storage, no waste. Jars barely reach the village shelf.",
      "defensible", "Some market-town households buy small pouches; the share cannot go much lower."),
    A("a-days-week", "Days in a week", "7", 7, "days", "physical-constant",
      "Converts a weekly habit into an average day.",
      "anchor", "—"),
    # triangulation inputs
    A("a-hot-cups", "Hot-beverage cups a day, per person in the band", "1.6", 1.6, "cups a day", "observed-behaviour",
      "Tea at home in the morning and evening for most, less for some; one and a half to two cups is the national habit. It puts India's coffee-age band at about 1.3 bn hot cups a day.",
      "judgement", "Winter and the northern states run higher; summer in the South lower."),
    A("a-coffee-share", "Coffee's share of those hot cups", "7%", 0.07, "share", "declared-judgement",
      "India is a tea country. Coffee is concentrated in the South and among young urban drinkers.",
      "shaky", "Southern states alone run far higher; the national blend is what matters here."),
    A("a-instant-share", "Instant's share of coffee cups", "35%", 0.35, "share", "declared-judgement",
      "Most of India's coffee is South Indian filter coffee; instant dominates everywhere else, but everywhere else drinks far less coffee.",
      "judgement", "Café and vending coffee are outside both sides of this share."),
    A("a-sachet-share", "Share of instant cups made from a sachet", "50%", 0.5, "share", "declared-judgement",
      "Taken as a single national figure here, which is the weakness of this route: the funnel derives it by geography.",
      "judgement", "The funnel implies about 55% nationally — urban half, rural nine-tenths — which is the number to compare against."),
]

coffee_calc = [
    line(1, "People in the coffee-drinking band", "1400000000 * 0.6", "1,400 Mn × 60%", "people", "840 Mn (84 crore)", ["a-pop", "a-age"],
         "Every line below is linear in this. Box it and split it once."),
    line(2, "Urban, in the band", "840000000 * 0.35", "840 Mn × 35%", "people", "294 Mn (29 crore)", ["a-urban-share"],
         "A third of the people and, as it turns out, four-fifths of the sachets."),
    line(3, "Rural, in the band", "840000000 * 0.65", "840 Mn × 65%", "people", "546 Mn (55 crore)", ["a-urban-share"],
         "Two-thirds of the people. Watch how little of the answer survives the rural funnel."),
    line(4, "Urban repeat buyers", "294000000 * 0.9 * 0.45 * 0.35", "294 Mn × 90% aware × 45% tried × 35% repeat", "buyers",
         "41.7 Mn (4.2 crore)", ["a-aware-u", "a-trial-u", "a-repeat-u"],
         "One urban adult in seven is a regular buyer. Most who try instant coffee go back to tea."),
    line(5, "Rural repeat buyers", "546000000 * 0.55 * 0.15 * 0.25", "546 Mn × 55% aware × 15% tried × 25% repeat", "buyers",
         "11.3 Mn (1.1 crore)", ["a-aware-r", "a-trial-r", "a-repeat-r"],
         "One rural adult in fifty. Awareness is over half; it is the 15% trial rate that does the damage."),
    line(6, "Urban cups a day", "41674500 * 4 / 7", "41.7 Mn × 4 cups a week ÷ 7", "cups a day", "2.38 crore cups",
         ["a-freq-u", "a-days-week"],
         "The frequency line. Replace four a week with one a day and this line rises 75% — more than any population figure could move it."),
    line(7, "Urban sachets a day", "23814000 * 0.5", "2.38 crore cups × 50% from sachets", "sachets a day", "1.19 crore sachets",
         ["a-sachet-u"],
         "Half the urban cups come out of jars and pouches. The sachet is the entry and convenience format, not the whole category."),
    line(8, "Rural cups a day", "11261250 * 2 / 7", "11.3 Mn × 2 cups a week ÷ 7", "cups a day", "32 lakh cups",
         ["a-freq-r", "a-days-week"],
         "A small base drinking occasionally."),
    line(9, "Rural sachets a day", "3217500 * 0.9", "32 lakh cups × 90% from sachets", "sachets a day", "29 lakh sachets",
         ["a-sachet-r"],
         "Almost every rural cup is a sachet — which is why the rural line is limited by trial, not by format or price."),
    line(10, "Sachets sold in India on an average day", "11907000 + 2895750", "1.19 crore urban + 29 lakh rural", "sachets a day",
         "≈ 1.5 crore — round it before you say it", [],
         "Say 1.5 crore a day, about 540 crore a year. The urban frequency and trial rates could each move it by half; nothing finer than two significant figures is defensible."),
]

coffee_tri = [
    line(1, "Hot cups a day in the band", "840000000 * 1.6", "840 Mn × 1.6 cups a day", "cups a day", "134 crore hot cups",
         ["a-hot-cups"], "The occasions base — overwhelmingly tea.", prefix="t"),
    line(2, "Coffee cups a day", "1344000000 * 0.07", "134 crore × 7% coffee", "cups a day", "9.4 crore coffee cups",
         ["a-coffee-share"], "Most of these are South Indian filter coffee.", prefix="t"),
    line(3, "Instant coffee cups a day", "94080000 * 0.35", "9.4 crore × 35% instant", "cups a day", "3.3 crore instant cups",
         ["a-instant-share"], "Instant is the smaller part of India's coffee, and the part this question is about.", prefix="t"),
    line(4, "Instant cups from a sachet", "32928000 * 0.5", "3.3 crore × 50% from sachets", "sachets a day", "1.65 crore sachets",
         ["a-sachet-share"], "Against 1.48 crore from the funnel.", prefix="t"),
]

coffee = {
    "id": "coffee-sachets-daily",
    "question": "How many single-serve instant coffee sachets are sold across India on an average day?",
    "tabLabel": "Coffee sachets, India daily",
    "archetype": "funnel-conversion-fmcg",
    "difficulty": "Medium",
    "timeboxMinutes": 12,
    "teachingPoint": "In a habit product, frequency does more work than the user count — and in a tea country, the trial rate is the number that binds. Run the funnel separately for urban and rural India, multiply the small repeat base by how often it actually drinks, and remember that a heavy drinker buys a jar, not sachets. Get the frequency wrong by a factor and no amount of care over the population will rescue the answer.",
    "scope": {
        "countingWhat": "Single-serve instant coffee sachets bought in India on an average day — the small one-cup packs sold for a few rupees each, including three-in-one premixes. Jars, refill pouches, filter coffee and coffee bought by the cup are out.",
        "unit": "sachets a day",
        "timeBasis": "flow (per day)",
        "geography": "All of India, run as two funnels — urban (35%) and rural (65%).",
        "included": [
            "Branded single-serve instant coffee sachets and three-in-one premixes",
            "Sachets bought for home, office desks, hostels and travel",
            "Sachets sold in strips at kiranas and paan shops",
        ],
        "excluded": [
            "Instant coffee in jars and refill pouches",
            "South Indian filter coffee and roast-and-ground powder",
            "Coffee bought by the cup — cafés, vending machines, office pantries",
            "Sachets exported",
        ],
        "boundaryTrap": "The category figure people half-remember is instant coffee as a whole, in tonnes or rupees — most of it jars and pouches bought by heavy urban drinkers. Sachets are a different, smaller business built on trial and affordability. Size the pack, not the category.",
    },
    "routeChoice": {
        "chosen": "Top-down",
        "why": "A consumer habit sizes best as a funnel from people: who is old enough, who has heard of it, who has tried it, who comes back, and how often they drink. Every gate is a number you can defend from what you see around you — and each one is a lever a brand can act on, which is what makes the answer useful after it is given.",
        "rejectedRoute": "Bottom-up",
        "rejectedWhyNot": "The supply side — instant coffee made in India, the share packed as sachets, sachets per kilo — needs trade figures a candidate cannot see or defend in the room. It is a good check for someone holding the data, and a guess dressed up as a calculation for anyone else.",
    },
    "tree": {
        "root": "Instant coffee sachets bought in India on an average day",
        "rootFormula": "= Σ (people in the band × aware × tried × repeat × cups a day × share from sachets), urban and rural separately",
        "value": "≈ 1.5 crore a day",
        "branches": [
            {"label": "Urban India — 29 crore people aged 15–60",
             "formula": "294 Mn × 90% aware × 45% tried × 35% repeat × 4 cups a week ÷ 7 × 50% from sachets",
             "value": "4.2 crore repeat buyers · 1.19 crore sachets a day",
             "note": "Four-fifths of the answer from a third of the people. Frequency is the lever that moves it most.",
             "isCriticalPath": True,
             "children": [
                 {"label": "Repeat buyers", "formula": "294 Mn × 90% × 45% × 35%", "value": "41.7 Mn",
                  "note": "One urban adult in seven. Most who try instant coffee go back to tea."},
                 {"label": "Cups a day", "formula": "41.7 Mn × 4 ÷ 7", "value": "2.38 crore",
                  "note": "Four a week blends daily desk drinkers with exam-season and weekend ones."},
                 {"label": "Share from sachets", "formula": "× 50%", "value": "1.19 crore sachets",
                  "note": "Heavy drinkers buy jars. The sachet is the entry and convenience format."},
             ]},
            {"label": "Rural India — 55 crore people aged 15–60",
             "formula": "546 Mn × 55% aware × 15% tried × 25% repeat × 2 cups a week ÷ 7 × 90% from sachets",
             "value": "1.1 crore repeat buyers · 29 lakh sachets a day",
             "note": "Two-thirds of the people and a fifth of the sachets. Trial, not price, is the binding number.",
             "isCriticalPath": False,
             "children": [
                 {"label": "Repeat buyers", "formula": "546 Mn × 55% × 15% × 25%", "value": "11.3 Mn",
                  "note": "The 15% trial rate does most of the damage; awareness is not the constraint."},
                 {"label": "Sachets a day", "formula": "11.3 Mn × 2 ÷ 7 × 90%", "value": "29 lakh",
                  "note": "Almost every rural cup comes from a sachet — it is the rural format."},
             ]},
        ],
    },
    "assumptions": coffee_assumptions,
    "calculation": coffee_calc,
    "finalAnswer": "≈ 1.5 crore sachets a day (about 15 Mn) — roughly 540 crore a year. Urban India buys four in five of them; rural India, with two-thirds of the people in the band, buys one in five, because far fewer rural drinkers have ever tried instant coffee.",
    "finalAnswerNumeric": 15000000,
    "answerBand": "70 lakh – 2.7 crore a day. The band is wide because it inherits roughly ±50% on urban frequency and a third either way on urban trial, and the two multiply. Population and awareness barely matter by comparison.",
    "orderOfMagnitude": "10^7 sachets a day (1.5 crore); about 5 × 10^9 a year",
    "triangulation": {
        "label": "Occasions cross-check — what share of India's hot cups could come out of a sachet?",
        "route": "Top-down",
        "premise": "Start from occasions instead of people: how many hot cups India's coffee-age band drinks in a day, what share are coffee, what share of the coffee is instant, and what share of the instant comes out of a sachet. The route shares only the population anchor with the funnel, so agreement is worth something — but it takes the sachet share as an input instead of deriving it, so it cannot explain why the urban and rural lines differ.",
        "lines": coffee_tri,
        "answer": "≈ 1.65 crore sachets a day, against 1.48 crore from the funnel.",
        "verdict": "Within about 11%, from two routes that share only the population figure — close enough to defend, not close enough to prove. The funnel stays the headline because its gates are levers a brand can pull: trial, repeat, frequency and format. The occasions route is a plausibility bound: it confirms that a coffee sachet is about one hot cup in ninety in a tea-first country, not that any particular gate is right.",
    },
    "sensitivity": {
        "assumptionId": "a-freq-u",
        "whyThisLever": "Frequency is the lever candidates most often underweight. They spend their care on the population and the funnel, then write 'one a day' or 'one a week' without noticing the two are seven times apart. Urban frequency moves four-fifths of the answer on its own.",
        "cases": [
            {"scenario": "Conservative", "leverValue": "2 cups a week", "answer": "≈ 88 lakh a day", "deltaVsBase": "−40%"},
            {"scenario": "Base", "leverValue": "4 cups a week", "answer": "≈ 1.48 crore a day", "deltaVsBase": "0%"},
            {"scenario": "Aggressive", "leverValue": "7 cups a week (daily)", "answer": "≈ 2.37 crore a day", "deltaVsBase": "+60%"},
        ],
        "breakpoint": "Doubling urban trial from 45% to 90% — every aware urban adult having tried it — adds 80% to the answer, more than moving urban drinkers from four cups a week to seven (+60%). Trial and frequency decide this question; the population anchor could be 5% out and change nothing that matters.",
        "oneLiner": "Every extra urban cup a week adds about 30 lakh sachets a day.",
    },
    "sanityChecks": [
        "1.48 crore a day is about 540 crore sachets a year — roughly four per Indian per year. A category most Indians never buy, bought steadily by a few, should look exactly like this.",
        "Across 5.3 crore repeat buyers, that is 0.28 sachets each a day — about two a week. A per-buyer figure above one a day would mean jar cups had been counted as sachet cups.",
        "Rural India holds 65% of the coffee-age band and buys 20% of the sachets. That gap is trial, not money: at a few rupees, a sachet is already the cheapest way into coffee there is.",
        "At about ₹3 a sachet, 540 crore sachets is roughly ₹1,600 crore a year at retail — a real category, and about a fifteenth of what urban India spends on packaged water.",
        "The occasions route puts a coffee sachet at about one hot cup in ninety. An answer implying one in ten would need coffee to have displaced tea across the North, which it plainly has not.",
        "Skip the funnel and assume every urban adult in the band drinks one sachet a day, and you answer 29 crore — twenty times too high. That error, more than any single assumption, is what the funnel exists to prevent.",
    ],
    "traps": [
        {"trap": "Treating everyone in the age band as a coffee drinker.",
         "whyItHappens": "The population step feels like the hard part, so once it is done the candidate multiplies straight through by a frequency.",
         "fix": "Gate on awareness, trial and repeat before anyone is allowed to drink. In urban India one adult in seven in the band is a regular buyer; in rural India, one in fifty."},
        {"trap": "Running one national funnel.",
         "whyItHappens": "A single set of rates is quicker, and an average feels safe.",
         "fix": "Split urban and rural before the first gate. Rural trial is a third of urban trial, and a national average hands rural India urban habits it does not have."},
        {"trap": "Guessing the frequency last, and carelessly.",
         "whyItHappens": "By the time the funnel is built the frequency feels like a detail, so 'one a day' goes in without a thought.",
         "fix": "Frequency moves the answer more than any population figure: one a day instead of four a week adds 60%. Blend heavy and light drinkers explicitly and say the number out loud."},
        {"trap": "Counting every instant coffee cup as a sachet.",
         "whyItHappens": "The question says instant coffee and sachet in one breath, so the two merge.",
         "fix": "Heavy urban drinkers buy jars and pouches because they cost less per cup. Apply a sachet share by geography — half in urban India, nearly all in rural — before you finish."},
        {"trap": "Using trial as the buying base.",
         "whyItHappens": "'Has tried it' and 'buys it' sound close, and trial rates are the figures people quote.",
         "fix": "Most triers go back to tea. Multiply by the repeat rate: 35% of urban triers and 25% of rural ones buy at least monthly."},
        {"trap": "Counting South India's coffee culture as sachet demand.",
         "whyItHappens": "India's coffee-drinking region is the first thing that comes to mind, and it inflates both awareness and trial.",
         "fix": "The South's habit is filter coffee, which this question excludes. It raises coffee's share of hot cups, not the sachet count — keep it out of the instant-coffee funnel."},
    ],
    "probes": [
        {"question": "Rural India is two-thirds of the people and a fifth of your sachets. As the brand, where do you invest?",
         "intent": "Whether the candidate reads a growth lever off the funnel instead of stopping at the number.",
         "goodAnswer": "Trial in rural India. Awareness is already over half and the sachet is already the affordable format, so the constraint is a first cup — sampling at haats and melas, distribution into smaller villages, a lower price point. Raising rural trial from 15% to 30% doubles the rural line; persuading urban drinkers to drink more is the harder and more expensive lever.",
         "weakAnswer": "Cut prices in rural India to make it affordable."},
        {"question": "Why does the sachet share fall as a drinker drinks more?",
         "intent": "Whether the candidate sees the sachet as an acquisition and convenience format, not the whole category.",
         "goodAnswer": "Because a jar or a pouch costs less per cup. A light drinker will not tie money up in a jar and wants no waste; a heavy drinker does the arithmetic and trades up. The sachet recruits and serves the occasional drinker and loses them to the jar as they become loyal — so a growing sachet line beside a flat jar line would be a warning, not good news.",
         "weakAnswer": "Sachets are more convenient."},
        {"question": "You were asked about an average day. What does that hide?",
         "intent": "Seasonality awareness.",
         "goodAnswer": "Hot drinks sell more in winter and the monsoon, and exam seasons move hostel demand. An average day hides the peak the supply chain actually has to meet; a brand planning production would want the peak week, not the mean.",
         "weakAnswer": "Nothing — I averaged it."},
        {"question": "A rival launches a ₹1 sachet. Which box in your funnel moves?",
         "intent": "Mapping a commercial move onto a specific gate.",
         "goodAnswer": "Trial first, especially in rural India, and then repeat among the lightest drinkers. Frequency among heavy drinkers hardly moves — they are on jars already. If the ₹1 sachet mostly takes existing sachet buyers, the sachet count rises while category value can fall.",
         "weakAnswer": "The whole market grows."},
        {"question": "Your two routes agree within 11%. Which would you defend to a client?",
         "intent": "Whether the candidate can separate a plausibility check from a decision model.",
         "goodAnswer": "The funnel, because every gate is something the client can act on — trial, repeat, frequency, format. The occasions route is a sense check that the answer is a plausible slice of India's hot drinks; it takes the sachet share as given, so it cannot explain the urban–rural gap, which is the most useful finding in the whole exercise.",
         "weakAnswer": "The one that gives the higher number."},
    ],
}

for d in (metro, coffee):
    io.open(f"content/guesstimates/{d['id']}.json", "w", encoding="utf-8").write(
        json.dumps(d, ensure_ascii=False, indent=2) + "\n")
    last = d["calculation"][-1]["result"]
    drift = abs(last - d["finalAnswerNumeric"]) / d["finalAnswerNumeric"]
    print(f"{d['id']}: {len(d['assumptions'])} assumptions, {len(d['calculation'])} calc + "
          f"{len(d['triangulation']['lines'])} triangulation lines; last line {last:,} vs "
          f"finalAnswerNumeric {d['finalAnswerNumeric']:,} ({drift*100:.1f}% apart); tabLabel {len(d['tabLabel'])} chars")
