export const interviewQuestionThemes = [
  {
    title: "Resource constraints & bricolage",
    range: "Questions 01—07",
    questions: [
      "When you initiated your venture, what were the most significant resource constraints you encountered—limited funding, skills, technology or market access?",
      "Describe a situation where you had to creatively “make do” with only the resources immediately available. What did you repurpose and adapt?",
      "How have your personal experiences, professional background or specialized skills helped overcome a challenge or create an opportunity?",
      "How have social networks, relationships or community connections helped you access resources otherwise unavailable?",
      "Have you combined seemingly disparate assets, ideas or waste materials to develop a novel solution, product or service?",
      "How has your approach to acquiring and using resources evolved as the company grew or faced new environmental pressure?",
      "What role does improvisation play in your problem-solving culture when circumstances or resource limits are unexpected?",
    ],
  },
  {
    title: "Effectuation & uncertainty",
    range: "Questions 08—13",
    questions: [
      "Did you begin with a rigid long-term plan, or did your vision and goals evolve as you learned and adapted?",
      "How did you use the resources, skills and networks you already possessed to take the first concrete steps?",
      "Describe an unexpected challenge, setback or mistake. How did you respond, and did it create a new opportunity or pivot?",
      "When committing time, money or effort, did you focus on potential gain or on what you were prepared to lose?",
      "How have formal or informal collaborations changed the trajectory or resource base of the business?",
      "How do you manage uncertainty? Do your actions shape future opportunities, or are you more reactive to external forces?",
    ],
  },
  {
    title: "Dynamic capabilities",
    range: "Questions 14—19",
    questions: [
      "How does the company systematically identify emerging opportunities or threats such as technologies, customer shifts or competitor moves?",
      "Describe a successful response to a major market disruption or technological shift. Which internal routines enabled it?",
      "Once an opportunity is identified, how do you mobilize internal talent and knowledge plus external funding and partnerships?",
      "How do structure, routines and skills stay agile and aligned with the market? When did you last reconfigure operations or the business model?",
      "Which routines support continuous learning from market feedback, successful initiatives and failures?",
      "How do you balance exploitation of existing competencies and products with exploration of new opportunities?",
    ],
  },
  {
    title: "Frugal innovation & jugaad",
    range: "Questions 20—31",
    questions: [
      "Who are the primary target customers, and which unmet needs or problems does the product or service address?",
      "How did you lower cost relative to alternatives while still meeting customer expectations?",
      "Which features or complexities did you remove or simplify, and why were they non-essential?",
      "How did you ensure adequate performance for the intended purpose and local conditions despite cost reductions?",
      "How did resource constraints influence innovation, and did they unexpectedly produce more creative solutions?",
      "How does the innovation embody the principle of doing more with less?",
      "Describe an improvised or makeshift solution created because conventional resources or methods were unavailable.",
      "How did you transform a specific scarcity—capital, infrastructure or specialised labour—into an innovation opportunity?",
      "Was the primary motivation a cheaper alternative, an underserved segment or something else?",
      "How important were simplicity and affordability, and which design, production or delivery choices achieved them?",
      "How have local resources, unconventional methods or existing technologies been recombined to create customer value?",
      "How does the jugaad mindset—flexibility, resourcefulness and ingenuity—show up in culture and decisions?",
    ],
  },
  {
    title: "Entrepreneurial orientation & creativity",
    range: "Questions 32—43",
    questions: [
      "How does the company support novel ideas, experimentation and new products, services or processes?",
      "Describe an emerging opportunity the company pursued before the trend became obvious.",
      "How are the risks of new ventures managed? Describe a bold decision and the reasoning behind it.",
      "How does culture support or hinder innovation, proactiveness and risk-taking?",
      "How do you balance stability and efficiency with exploration and calculated risk?",
      "How does compensation or recognition encourage—or discourage—sensible risk and innovation?",
      "Describe a truly novel idea that significantly changed the business direction or offering.",
      "Which practices foster creative thinking when the problem is complex?",
      "How do you approach a problem with no obvious solution and connect seemingly unrelated concepts?",
      "How are novel ideas implemented and brought to market despite difficulties?",
      "How do personal background, experience or cognitive strengths help you see opportunities others miss?",
      "Describe a constraint that unexpectedly spurred a highly creative solution.",
    ],
  },
  {
    title: "Stakeholder strategy",
    range: "Questions 44—50",
    questions: [
      "Who are the most critical stakeholders, especially early on—customers, employees, investors, suppliers, community or government?",
      "How did you engage those stakeholders to secure funding, talent, partnerships or market access?",
      "Describe a time when stakeholder expectations conflicted. How did you navigate the tension?",
      "How do you build customer loyalty and advocacy beyond transactional interactions?",
      "How do you create transparency and trust with investors and employees during uncertainty or major change?",
      "How do mission and values account for the wider community or society?",
      "When has a strong stakeholder relationship created an unexpected benefit or opportunity?",
    ],
  },
  {
    title: "Performance & current challenges",
    range: "Questions 51—58",
    questions: [
      "How is success defined, and which financial and non-financial metrics are tracked?",
      "What have been the main drivers of revenue and profitability over the last one to three years?",
      "Which operational indicators—customer satisfaction, delivery, quality or efficiency—matter most, and how are they improved?",
      "How do you assess the growth trajectory, and which factors have been most important to sustained growth?",
      "What is difficult about measuring performance as a startup, regular company or SME, and how have you addressed it?",
      "How is performance communicated to investors, employees, customers and other stakeholders?",
      "How have innovation, proactiveness and stakeholder engagement directly affected firm performance?",
      "What current regulatory, growth or other strategic challenges is the company facing?",
    ],
  },
] as const;
